<?php
header("Content-Type: application/json; charset=utf-8");
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Pragma: no-cache");

session_set_cookie_params(0, "/FoodConnect", "", false, true);
require_once __DIR__ . "/session_config.php";
require_once __DIR__ . "/db.php";

function respond_json(array $data, int $statusCode = 200): void
{
    http_response_code($statusCode);
    echo json_encode(
        $data,
        JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
    );
    exit;
}

if (!isset($conn) || !($conn instanceof mysqli)) {
    respond_json([
        "success" => false,
        "message" => "Service is temporarily unavailable. Please try again shortly."
    ], 500);
}

if (
    empty($_SESSION["user_id"]) ||
    empty($_SESSION["restaurant_id"])
) {
    $conn->close();

    respond_json([
        "success" => false,
        "message" => "Your session has expired or you do not have access. Please log in again."
    ], 401);
}

$data = json_decode(
    file_get_contents("php://input"),
    true
);

if (!is_array($data)) {
    $data = $_POST;
}

$restaurant_id = (int)$_SESSION["restaurant_id"];
$user_id = (int)$_SESSION["user_id"];
$user_role = strtolower(
    trim((string)($_SESSION["role"] ?? ""))
);

if (
    $restaurant_id <= 0 ||
    $user_id <= 0 ||
    $user_role === ""
) {
    $conn->close();

    respond_json([
        "success" => false,
        "message" => "Invalid user session."
    ], 401);
}

$action_type = trim(
    (string)($data["action_type"] ?? "")
);

/* =========================================================
   MANUAL RECEIPT / KITCHEN PRINT ACCOUNTABILITY

   This special activity type is generated by the two manual
   cashier buttons only. The server builds the title and
   description itself so the browser cannot claim a different
   order, restaurant, staff name, or document label.
========================================================= */

if ($action_type === "receipt_print_request") {
    if (!in_array($user_role, ["cashier", "owner"], true)) {
        $conn->close();

        respond_json([
            "success" => false,
            "message" => "You are not authorized to log receipt print requests."
        ], 403);
    }

    $order_id = (int)($data["order_id"] ?? 0);
    $document_type = strtolower(
        trim((string)($data["document_type"] ?? ""))
    );

    $documentLabels = [
        "customer_receipt" => "Customer receipt",
        "kitchen_ticket" => "Kitchen ticket"
    ];

    if (
        $order_id <= 0 ||
        !isset($documentLabels[$document_type])
    ) {
        $conn->close();

        respond_json([
            "success" => false,
            "message" => "Invalid receipt print request."
        ], 400);
    }

    /*
     * Mandatory multi-restaurant validation.
     * Even if an order ID is changed in the browser request,
     * it can only be logged when that order belongs to the
     * authenticated restaurant.
     */
    $orderStmt = $conn->prepare("
        SELECT order_id
        FROM tbl_orders
        WHERE order_id = ?
          AND restaurant_id = ?
        LIMIT 1
    ");

    if (!$orderStmt) {
        $conn->close();

        respond_json([
            "success" => false,
            "message" => "Unable to validate the order for activity logging."
        ], 500);
    }

    $orderStmt->bind_param(
        "ii",
        $order_id,
        $restaurant_id
    );

    if (!$orderStmt->execute()) {
        $orderStmt->close();
        $conn->close();

        respond_json([
            "success" => false,
            "message" => "Unable to validate the order for activity logging."
        ], 500);
    }

    $orderExists =
        $orderStmt->get_result()->fetch_assoc();

    $orderStmt->close();

    if (!$orderExists) {
        $conn->close();

        respond_json([
            "success" => false,
            "message" => "Order not found for this restaurant."
        ], 404);
    }

    /*
     * Resolve the staff name from the database instead of
     * trusting a name sent by JavaScript.
     */
    $staffName = "Cashier";

    $userStmt = $conn->prepare("
        SELECT TRIM(CONCAT_WS(' ', NULLIF(TRIM(first_name), ''), NULLIF(TRIM(middle_name), ''), NULLIF(TRIM(last_name), ''))) AS display_name
        FROM tbl_users
        WHERE user_id = ?
          AND restaurant_id = ?
        LIMIT 1
    ");

    if ($userStmt) {
        $userStmt->bind_param(
            "ii",
            $user_id,
            $restaurant_id
        );

        if ($userStmt->execute()) {
            $userRow =
                $userStmt->get_result()->fetch_assoc();

            $resolvedName = trim(
                (string)($userRow["display_name"] ?? "")
            );

            if ($resolvedName !== "") {
                $staffName = $resolvedName;
            }
        }

        $userStmt->close();
    }

    $documentLabel =
        $documentLabels[$document_type];

    $roleLabel = $user_role === "owner"
        ? "Owner"
        : "Cashier";

    $action_title =
        $documentLabel . " Print Requested";

    $action_description = sprintf(
        "%s print requested for Order #%d by %s (%s).",
        $documentLabel,
        $order_id,
        $staffName,
        $roleLabel
    );

    $insertStmt = $conn->prepare("
        INSERT INTO tbl_activity_logs
        (
            restaurant_id,
            user_id,
            user_role,
            action_type,
            action_title,
            action_description
        )
        VALUES (?, ?, ?, ?, ?, ?)
    ");

    if (!$insertStmt) {
        $conn->close();

        respond_json([
            "success" => false,
            "message" => "Unable to prepare receipt print activity log."
        ], 500);
    }

    $insertStmt->bind_param(
        "iissss",
        $restaurant_id,
        $user_id,
        $user_role,
        $action_type,
        $action_title,
        $action_description
    );

    if (!$insertStmt->execute()) {
        $insertStmt->close();
        $conn->close();

        respond_json([
            "success" => false,
            "message" => "Failed to save receipt print activity log."
        ], 500);
    }

    $log_id = (int)$insertStmt->insert_id;

    $insertStmt->close();
    $conn->close();

    respond_json([
        "success" => true,
        "message" => "Receipt print request logged.",
        "log_id" => $log_id
    ]);
}

/* =========================================================
   EXISTING GENERIC ACTIVITY-LOG BEHAVIOR

   Preserved for current FoodConnect features that already use
   add_activity_log.php with action_title/action_description.
========================================================= */

$action_title = trim(
    (string)($data["action_title"] ?? "")
);

$action_description = trim(
    (string)($data["action_description"] ?? "")
);

if (
    $action_type === "" ||
    $action_title === "" ||
    $action_description === ""
) {
    $conn->close();

    respond_json([
        "success" => false,
        "message" => "Missing required fields."
    ], 400);
}

$stmt = $conn->prepare("
    INSERT INTO tbl_activity_logs
    (
        restaurant_id,
        user_id,
        user_role,
        action_type,
        action_title,
        action_description
    )
    VALUES (?, ?, ?, ?, ?, ?)
");

if (!$stmt) {
    $conn->close();

    respond_json([
        "success" => false,
        "message" => "Unable to prepare activity log."
    ], 500);
}

$stmt->bind_param(
    "iissss",
    $restaurant_id,
    $user_id,
    $user_role,
    $action_type,
    $action_title,
    $action_description
);

if ($stmt->execute()) {
    $log_id = (int)$stmt->insert_id;

    $stmt->close();
    $conn->close();

    respond_json([
        "success" => true,
        "message" => "Activity log saved.",
        "log_id" => $log_id
    ]);
}

$stmt->close();
$conn->close();

respond_json([
    "success" => false,
    "message" => "Failed to save activity log."
], 500);
?>
